# -*- coding: utf-8 -*-
"""data_fetcher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oyn6cU-k301-aHcluMZhCw_s0JH2oqLX
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd
BASE_DIR = "/content/drive/MyDrive/property_valuation_mapbox"
IMAGE_DIR = os.path.join(BASE_DIR, "images/train")

os.makedirs(IMAGE_DIR, exist_ok=True)

print("Saving images to:", IMAGE_DIR)

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/gorilla15a/property-valuation-multimodal.git
# %cd property-valuation-multimodal

train = pd.read_csv("data/processed/train_eda.csv")

train = train[["id", "lat", "long"]].dropna()
print("Total properties:", len(train))

import requests
from PIL import Image
from io import BytesIO

MAPBOX_TOKEN = "pk.eyJ1IjoiYW5zdWwxNSIsImEiOiJjbWpqdzU0ZGkyOGtkM2dzaHE3OXFsY2s5In0.XyW3nK-0bpYPwM72i9F0aQ"

def fetch_mapbox_image(lat, lon, save_path, zoom=18, size=256):
    url = (
        f"https://api.mapbox.com/styles/v1/"
        f"mapbox/satellite-streets-v12/static/"
        f"{lon},{lat},{zoom}/"
        f"{size}x{size}"
        f"?access_token={MAPBOX_TOKEN}"
    )

    response = requests.get(url, timeout=10)

    if response.status_code != 200:
        print("Failed:", response.status_code)
        print(response.text[:200])
        return False

    img = Image.open(BytesIO(response.content))
    img.save(save_path)
    return True

row = train.iloc[0]

test_path = os.path.join(IMAGE_DIR, f"{row['id']}.png")

success = fetch_mapbox_image(
    row["lat"],
    row["long"],
    test_path
)

print("Success:", success)

import time
from tqdm import tqdm

FAILED = []

for _, row in tqdm(train.iterrows(), total=len(train)):
    img_path = os.path.join(IMAGE_DIR, f"{row['id']}.png")

    # Skip if already downloaded
    if os.path.exists(img_path):
        continue

    ok = fetch_mapbox_image(
        row["lat"],
        row["long"],
        img_path
    )

    if not ok:
        FAILED.append(row["id"])

    time.sleep(0.05)  # IMPORTANT: avoid rate limits

import os

IMAGE_DIR = "/content/drive/MyDrive/property_valuation_mapbox/images/train"

num_images = len([
    f for f in os.listdir(IMAGE_DIR)
    if f.endswith(".png")
])

print("Number of images downloaded:", num_images)

num_ids = train["id"].nunique()

print("Number of unique property IDs:", num_ids)
print("Images missing:", num_ids - num_images)

import pandas as pd
test = pd.read_csv(
    "/content/property-valuation-multimodal/data/processed/test_eda.csv"
)
test = test[["id", "lat", "long"]].dropna()
print("Test samples:", len(test))

TEST_IMAGE_DIR = "/content/drive/MyDrive/property_valuation_mapbox/images/test"
os.makedirs(TEST_IMAGE_DIR, exist_ok=True)

import time
from tqdm import tqdm

FAILED_TEST = []

for _, row in tqdm(test.iterrows(), total=len(test)):
    img_path = os.path.join(TEST_IMAGE_DIR, f"{row['id']}.png")

    if os.path.exists(img_path):
        continue

    ok = fetch_mapbox_image(
        row["lat"],
        row["long"],
        img_path
    )

    if not ok:
        FAILED_TEST.append(row["id"])

    time.sleep(0.05)

import os

IMAGE_DIR = "/content/drive/MyDrive/property_valuation_mapbox/images/train"

for fname in os.listdir(IMAGE_DIR):
    if fname.endswith(".png") and ".0.png" in fname:
        old_path = os.path.join(IMAGE_DIR, fname)
        new_name = fname.replace(".0.png", ".png")
        new_path = os.path.join(IMAGE_DIR, new_name)
        os.rename(old_path, new_path)

print("Renaming done.")

IMAGE_DIR = "/content/drive/MyDrive/property_valuation_mapbox/images/test"
for fname in os.listdir(IMAGE_DIR):
    if fname.endswith(".png") and ".0.png" in fname:
        old_path = os.path.join(IMAGE_DIR, fname)
        new_name = fname.replace(".0.png", ".png")
        new_path = os.path.join(IMAGE_DIR, new_name)
        os.rename(old_path, new_path)
print("Renaming done.")